export const SET_COINS_TYPE = "SET_COINS";
export const SET_COUNTRIES_TYPE = "SET_COUNTRIES";
export const SET_COMPOSITION_TYPE = "SET_COMPOSITION";
export const SET_QUALITY_TYPE = "SET_QUALITY";
export const SET_SEARCH_TYPE = "SET_SEARCH";
export const SET_ADVANCED_SEARCH_TYPE = "SET_ADVANCED_SEARCH";




